### PR TITLE
fix dynamic linking with MSVC

### PR DESCRIPTION
**Pull request by Be-ing**
fixing this error:
error LNK2001: unresolved external symbol "struct _sbsms_::SBSMSQualityParams const _sbsms_::SBSMSQualityStandard" (?SBSMSQualityStandard@_sbsms_@@3USBSMSQualityParams@1@B)

### CODE REVIEW

**Comment by lllucius** [comment]
Why is this needed?  Sorry, I don't have time to try it just now, but what happens if you use the "_sbsms_" namespace.  Audacity does it that way and this was a spinoff from the Audacity sources.

**Comment by Be-ing** [comment]
The SBSMSQualityParams is not even used directly in SBSMSEffect.cpp so that would not help. I got the error I posted in the original post when trying to link version 2.3.0 dynamically with MSVC.

**Comment by lllucius** [comment]
> 
> 
> The SBSMSQualityParams is not even used directly in SBSMSEffect.cpp so that would not help.

Looks like it is to me:

[diablo:~/audacity/src/effects]$ grep -r SBSMSQualityStandard
SBSMSEffect.cpp:              rb.quality = std::make_unique<SBSMSQuality>(&SBSMSQualityStandard);

**Comment by Be-ing** [comment]
Hm, not sure how I missed that. Anyway, I don't know how adding the namespace prefix would solve this link error. Even if it did, I don't think that would be a great solution considering only this one symbol would require it. I have already confirmed the solution in this branch works on Windows, macOS, and Linux.

**Comment by carlo-bramini** [comment]
I don't know if it could be helpful, but I generated with CMake-GUI the solution files and then I compiled sbsms.dll with VS2017, VS2019 and VS2022 without any error.

**Comment by claytonotey** [comment]
Thanks.  I screwed up a resolve when merging, but then fixed it.

**Pull request merged**
